# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='canlist',
            field=models.BooleanField(default=True),
        ),
    ]
