# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_categoriesmodel_canlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='can_duoshuo',
            field=models.BooleanField(default=True),
        ),
    ]
